services:
  db:
    container_name: db-container
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  api:
    container_name: api-container
    build: ./api
    image: cloakingghost/api:lst
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - db-network
      - api-network
    depends_on:
      db:
        condition: service_healthy
  client:
    container_name: client-container
    build: ./client
    image: cloakinghost/client:lts
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    networks:
      - api-network

volumes:
  db-volume:

networks:
  db-network:
  api-network: