name : Deploy Service

on: 
 push:
  branches:
    - main


jobs:
  docker-build-push:
    runs-on: ubuntu-24.04
    steps:



      - name: Login DockerHub
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
